import { Nunito } from "next/font/google";
import "./globals.css";
import { AppContextProvider } from "@/context/AppContext";
import { Toaster } from "react-hot-toast";
import { ClerkProvider } from "@clerk/nextjs";

const nunito = Nunito({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

export const metadata = {
  title: "Kids Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    
    <html lang="en">
      <body
       suppressHydrationWarning
       
        className={`${nunito.className} bg-[var(--background)] text-[var(--text-color)] max-w-7xl mx-auto min-h-screen`}
      >
        <ClerkProvider>
         <Toaster/>
        <AppContextProvider>{children}</AppContextProvider>
        </ClerkProvider>
      </body>
    </html>
    
  );
}
